title: ''
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bda20203-2132-4b5f-a791-37e436823dd2.jpg
color:
  saturation: 0.7129322
  brandStrength: 0.3422189643606544
  lightness: 0.1735284
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.7094522
typography_spectrum: 0.5064447
description: inside | outside
navigation:
  - name: outside
    id: 7b3094d8-6a72-47d9-a4fd-b8b1f6f103e6
    type: content
  - name: inside
    id: 9cfc725a-0794-4b7a-b1a1-32a1602da490
    type: content
layout_spectrum: 0.003759398
name: RYN photography
